export const data = [
  {
    title: "$111.00",
    description: "Razero Wolverine ",
    id: 1,
    img: "/razero wolverine.webp",
  },
  {
    title: "$79.99",
    description: "Ninotendo Switch Joy-Con Controllers",
    id: 2,
    img: "/nino tendo.webp",
  },
  {
    title: "$500.00-850.00",
    description: "Razero Playstation VR",
    id: 3,
    img: "/playstation.webp",
  },
  {
    title: "$1850.00-1850.00",
    description: "Makbook Pro M1",
    id: 4,
    img: "/macbook pro m1.webp",
  },
  {
    title: "$930.00",
    description: "Makbook Air M1",
    id: 5,
    img: "/macbook air m1.webp",
  },
  {
    title: "$710.00",
    description: "Makbook Air 2019",
    id: 6,
    img: "/macbook air 2019.webp",
  },
  {
    title: "$750.00",
    description: "Azsus VivaBook Pro 15",
    id: 7,
    img: "/asus pro 15.webp",
  },
  {
    title: "$215.00",
    description: "Azsus VG279Q Gaming Monitor",
    id: 8,
    img: "/asus vg279q.webp",
  },
  {
    title: "$325.00",
    description: "Azsus ProArt PA329Q Professional Monitor",
    id: 9,
    img: "/asus proart.webp",
  },
  {
    title: "$255.00",
    description: "Azsus ROG Swift PG279QZ Gaming Monitor",
    id: 10,
    img: "/asus rog.webp",
  },
  {
    title: "$66.00",
    description: "Fanytech VX7 Crypto Mouse",
    id: 11,
    img: "/fanytech.webp",
  },
  {
    title: "$50.00",
    description: "HypereX Pulsefire Haste 2",
    id: 12,
    img: "/hyperX.webp",
  },
  {
    title: "$67.99",
    description: "Loogitech Powered Wireless Charging Stand",
    id: 13,
    img: "/logeitech.webp",
  },
  {
    title: "$53.00",
    description: "Samusung SoundPal S8 Mini Bluetooth Speaker",
    id: 14,
    img: "/samsung soundpal.webp",
  },
  {
    title: "$24.00",
    description: "JuBL BOOSTUP Wireless Charging Pad",
    id: 15,
    img: "/jubl.webp",
  },
  {
    title: "$110.00",
    description: "JuBL X100 Mini Bluetooth Speaker",
    id: 16,
    img: "/jubl x100.webp",
  },
  {
    title: "$118.00",
    description: "JuBL Charge 5",
    id: 17,
    img: "/jubl charge 5.webp",
  },
  {
    title: "$250.00",
    description: "Souny SRS-XB43 Bluetooth Speaker",
    id: 18,
    img: "/souny srs.webp",
  },
  {
    title: "$450.00",
    description: "Aamazfit Soundcore Flare",
    id: 19,
    img: "/aamazfil soundcore.webp",
  },
  {
    title: "$199.00",
    description: "Aamazfit Verge Lite",
    id: 20,
    img: "/aamaz verge.webp",
  },
  {
    title: "$190.00-$190.00",
    description: "Aamazfit Verge Lite",
    id: 21,
    img: "/aamaz verge2.webp",
  },
  {
    title: "$256.00",
    description: "Samsung Galaxy Watch 4",
    id: 22,
    img: "/samsung galaxy.webp",
  },
  {
    title: "$231.00",
    description: "Aamazfit Bip U",
    id: 23,
    img: "/aamaz bit u.webp",
  },
  {
    title: "$310.00",
    description: "Aamazfit T-Rex",
    id: 24,
    img: "/aamaz t-rex.webp",
  },
  {
    title: "$197.99",
    description: "UROGREEN Dash Cam 66W",
    id: 25,
    img: "/green.webp",
  },
  {
    title: "$106.00",
    description: "Ziaomi Mijia Lite Action Camera",
    id: 26,
    img: "/ziaomi.webp",
  },
  {
    title: "$250.00",
    description: "fuojifilm Instax Square SQ6",
    id: 27,
    img: "/fuojifilm.webp",
  },
  {
    title: "$90.00",
    description: "Logeitech C930e Business Webcam",
    id: 28,
    img: "/loogitech.webp",
  },
  {
    title: "$274.00",
    description: "Samsung WB1100F Digital Camera",
    id: 29,
    img: "/samsung wb110.webp",
  },
  {
    title: "$25.00",
    description: "Anyker Soundcore R500 Bluetooth Neckband Earphone",
    id: 30,
    img: "/anyker.webp",
  },
];
